# Generated by Django 5.2.4 on 2026-05-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="poll",
            new_name="votes_poll_created_7e011a_idx",
            old_name="votes_poll_created_by_id_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="poll",
            new_name="votes_poll_expires_c0c0f3_idx",
            old_name="votes_poll_expires_at_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="polloption",
            new_name="votes_pollo_poll_id_35823b_idx",
            old_name="votes_pollo_poll_id_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="vote",
            new_name="votes_vote_poll_id_970dd7_idx",
            old_name="votes_vote_poll_id_user_id_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="vote",
            new_name="votes_vote_user_id_114521_idx",
            old_name="votes_vote_user_id_123456_idx",
        ),
    ]
