"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from decouple import config
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-pm!a_g##2sh2km+qgdib%rjs*3xglpx2+#)(ew#n__q=h2g9x7')

# SECURITY WARNING: don't run with debug turned on in production!
IS_VERCEL = os.environ.get("VERCEL") == "1"
IS_RENDER = "RENDER" in os.environ
DEBUG = not (IS_VERCEL or IS_RENDER) and config("DEBUG", default=True, cast=bool)

def _split_env_list(name: str, default: str) -> list[str]:
    """Vercel may inject empty strings; treat them as unset."""
    raw = os.environ.get(name, "").strip() or config(name, default=default)
    return [part.strip() for part in raw.split(",") if part.strip()]


ALLOWED_HOSTS = _split_env_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,.vercel.app",
)
if vercel_url := os.environ.get("VERCEL_URL"):
    ALLOWED_HOSTS.append(vercel_url.strip())

CSRF_TRUSTED_ORIGINS = _split_env_list(
    "CSRF_TRUSTED_ORIGINS",
    (
        "https://*.vercel.app,"
        "https://community-wine-iota.vercel.app,"
        "http://localhost:8000,"
        "http://127.0.0.1:8000"
    ),
)
if vercel_url:
    CSRF_TRUSTED_ORIGINS.append(f"https://{vercel_url.strip()}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # 서드파티
    "crispy_forms",
    "crispy_tailwind",
    "django_htmx",

    # 로컬 앱
    "apps.accounts",
    "apps.notices",
    "apps.board",
    "apps.calendar_app",
    "apps.votes",
    "apps.surveys",
    "apps.search",
    "apps.dashboard",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _first_env(*names: str) -> str:
    for name in names:
        value = os.environ.get(name, "").strip()
        if value:
            return value
    return ""


# Supabase/Vercel/Render often expose postgres URL under alternate keys
DATABASE_URL = _first_env(
    "DATABASE_URL",
    "POSTGRES_URL",
    "POSTGRES_PRISMA_URL",
    "SUPABASE_DB_URL",
) or config("DATABASE_URL", default="")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
elif IS_VERCEL or IS_RENDER:
    # Vercel build runs build.py without DATABASE_URL; use in-memory DB for that step only.
    _is_vercel_build = any("build.py" in (arg or "") for arg in sys.argv)
    if _is_vercel_build:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": ":memory:",
            }
        }
    else:
        raise ImproperlyConfigured(
            "DATABASE_URL is required on Vercel/Render. "
            "Connect Supabase (ijzifreevyhgndqasokn) and set DATABASE_URL in environment variables."
        )
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "ATOMIC_REQUESTS": True,
            "OPTIONS": {
                "timeout": 20,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Vercel / reverse proxy HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CustomUser (AbstractUser 확장)
AUTH_USER_MODEL = "accounts.CustomUser"

# SQLite 데이터베이스 최적화 신호 등록
# (연결 생성 시 WAL, Foreign Keys 활성화)
import django
from django.db.backends.signals import connection_created
from django.dispatch import receiver


@receiver(connection_created)
def optimize_sqlite(sender, connection, **kwargs):
    """SQLite 연결 최적화 설정"""
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()

        # 1. WAL 모드 활성화: 읽기/쓰기 동시성 극대화
        cursor.execute('PRAGMA journal_mode=WAL;')

        # 2. 외래 키 제약 조건 활성화: 데이터 무결성 보장
        cursor.execute('PRAGMA foreign_keys=ON;')

        # 3. Synchronous 모드: NORMAL로 설정 (성능과 안정성 균형)
        cursor.execute('PRAGMA synchronous=NORMAL;')

        # 4. Cache size: 64MB로 증가 (성능 향상)
        cursor.execute('PRAGMA cache_size=-64000;')

        # 5. TEMP_STORE: 메모리에 임시 테이블 저장 (성능 향상)
        cursor.execute('PRAGMA temp_store=MEMORY;')

        cursor.close()
